#!/usr/bin/python3

import os
import socket
import sys
from slack_webhook import Slack

class Program:
    def __init__(self):
        self.icon = ':slack:'

    def run(self):
        self.__parseArgs()
        self.__parseUrl()
        self.__parseUsers()
        self.slack = Slack(url=self.url)
        self.__postMessage()

    def __parseArgs(self):
        args = sys.argv.copy()
        args.pop(0)
        icons = {
                '-ok': ":heavy_check_mark:",
                '-slack': ":slack:",
                '-info': ":slack:",
                '-warning': ":warning:",
                '-error': ":bangbang:",
        }
            
        if args[0] in icons:
            self.icon = icons.get(args[0])
            args.pop(0)

        self.message = ' '.join(args)

    def __parseUrl(self):
        assert 'SLACK_URL' in os.environ
        self.url = os.environ['SLACK_URL']

    def __parseUsers(self):
        if 'SLACK_NOTIFY_USERS' not in os.environ:
            self.users = []
            return
            
        self.users = os.environ['SLACK_NOTIFY_USERS'].split(',')

    def __postMessage(self):
        self.slack.post( text=self.__formatMessage(), link_names=True )

    def __formatMessage(self):
        return " ".join([
            self.icon,
            self.__formatNotifyUsers(),
            self.message
        ])

    def __formatNotifyUsers(self):
        usersWithAt = map(lambda x: '@'+x, self.users);
        return " ".join( usersWithAt )

p = Program()
sys.exit( p.run() )
